"""changed meeting to use order for best timeslot

Revision ID: c67228dd58f8
Revises: 
Create Date: 2025-04-27 14:34:59.105621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c67228dd58f8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_timeslot', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_meeting_best_timeslot', type_='foreignkey')
        batch_op.drop_column('best_timeslot_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('best_timeslot_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_meeting_best_timeslot', 'timeslot', ['best_timeslot_id'], ['id'])
        batch_op.drop_column('best_timeslot')

    # ### end Alembic commands ###
